### ISSUE TITLE
Is it possible to play audio when Do Not Disturb mode is on, but not in silent mode?

### ISSUE THREAD

**Issue by corey-sobel** [ryanheise/audio_session#116]
Are there `AudioSessionConfiguration` recipes that make it such that audio will not play while the phone is in silent mode but will play while in "Do Not Disturb" mode?

For example: `AudioSessionConfiguration.music()` will play in both silent mode and do not disturb mode.

I have audio configurations that will respect silent mode, but then sound will not play while do not disturb mode is on.

Is the behavior I'm asking for something that is possible on iOS and/or Android?

Thanks for your help!

**Comment by ryanheise** [comment]
I can't provide advice on how to use Android's and iOS's APIs, although you might be able to find the iOS/Android expertise by asking (2 separate questions) on StackOverflow (or searching existing questions). Since the native APIs are wrapped, you will be better off asking questions about the native APIs than asking specifically about Flutter.
