### ISSUE TITLE
OSStatus error 561017449

### ISSUE THREAD

**Issue by SmartfySolutions** [ryanheise/audio_session#136]
Hello.

I have a Flutter App in production using audio_session ^0.1.19. I use Flutter 3.22.2.
On some iOS users I have picked up the following error in Crashlytics when running session.configure():

PlatformException(561017449, The operation couldn't be completed. (OSStatus error 561017449.), null, null) 

I have not been able to replicate it on my devices.
Do you know what could be the cause?
Has it happened to anyone else?

Best regards

**Comment by ryanheise** [comment]
audio_session just directly returns whatever error code the underlying operating system gives. If you look up Apple's documentation, it should provide the meanings of the different error codes, or if you Google for that number (561017449), you'll get some answers. For example:

https://forums.developer.apple.com/forums/thread/682474

`"The app was not allowed to set the audio category because another app (Phone, etc.) is controlling it."`
