### ISSUE TITLE
How to  pause other App Player then resume

### ISSUE THREAD

**Issue by faizanmohdizi** [ryanheise/audio_session#142]
hi ,i am using just audio with audio session and audio service in my app.

i want to implement the functionality like this .

other app like (Spotify ,You tube music ) playing audio
now in between my app with just_audio player started playing audio in background.
now other app player ((Spotify ,You tube music ) should pause Until my app audio is playing.
after my app audio will stop then other app audio should resume where it left.

is it possible with just_audio .if it is then where i need to change.

**Comment by ryanheise** [comment]
I can give you a quick answer to part of your requirements: If you call `setActive` when you start playing audio in your own app (which is the default with just_audio, since by default it manages the audio session for you), it should stop Spotify and YouTube Music.

The other requirement to resume Spotify/YouTube Music after you are finished is a bit more complicated because the possibilities differ for iOS and Android. I recommend you to ask that question on StackOverflow regarding the platform specific APIs. E.g. One question about how to do it based on Android's AudioManager, and another question about how to do it based on iOS's AVAudioSession. This package exposes both APIs, so once you have your answer, you'll be able to implement it via this plugin's API.

**Comment by faizanmohdizi** [comment]
Thank @ryanheise for the help.

**Comment by faizanmohdizi** [comment]
i have achieved this on android by setting session configuration androidAudioFocusGainType:AndroidAudioFocusGainType.gainTransient, 


but for ios i am not getting suitable option if you can help ,how can i get the same on ios 

Thanks!

**Comment by ryanheise** [comment]
As I indicated above, iOS doesn't provide the same options as Android, but to investigate further I suggest going to StackOverflow.
