### ISSUE TITLE
[Question] Audio player becomes unresponsive when paused for too long

### ISSUE THREAD

**Issue by swiftymf** [ryanheise/audio_session#42]
I’m using just_audio and audio_service for radio streaming app I’m building. 

It uses an HLS stream and when I pause the audio with the phone locked, if I wait a couple minutes to hit play again the audio player (?) stops working. 
- The lockscreen controls go grey after Play is tapped.
- The player controls in the app don’t play audio. The UI is still good, can use print statements, etc. The audio handler Play method is also being called, but the player doesn't respond. 

I’m wondering if this has to do with using an HLS stream. It still seems less common and I can’t find others with this issue online anywhere. The amount of time it takes between pausing and things breaking seems to relate somewhat to the amount of buffer that exists. For example, if only 45 seconds of audio has been buffered and we are paused for 1 minute, things will break. Paused less than a minute and everything works fine. 

I’ve tried running in Xcode to see if anything shows up in the console. There are some logs, but nothing seems directly related. I’m happy to provide what’s there if it could help.

**Comment by ryanheise** [comment]
Closing this issue since it does not conform to the issue template.

Since you are asking a question, please click on the "New issue" button in the top right and then select the "Ask a question" link. I am not actually sure what you clicked on, but it was not the "Ask a question" link because that should not have resulted in this issue.
