### ISSUE TITLE
example depends on path_provider_ios which is renamed and there is no path_provider_ios

### ISSUE THREAD

**Issue by insignity** [ryanheise/audio_session#80]
Hello, can you fix this?
<img width="1039" alt="Снимок экрана 2023-01-31 в 10 07 55" src="https://user-images.githubusercontent.com/19279660/215660701-22e55e40-22ce-4f08-a281-7a5ef92dd792.png">

**Comment by ryanheise** [comment]
By any chance, did you use audio_session successfully in the past, and then found that it started giving this error recently?

**Comment by ryanheise** [comment]
I will note that the `*.lock` files are not checked into the git repository for `audio_session`, which is why I think this must be an issue with your own lock files. My theory is that your lock files point to an old dependency, and once you re-resolve the dependencies to the latest versions, the error should go away. E.g. `flutter pub upgrade`.

**Comment by ryanheise** [comment]
It seems in the example directory the pubspec lock file isn't checked in but the Podfile lock file is, so I can remove that. However, the pubspec lock file is primary and the podfile lock file is secondary, so if you fix your pubspec lock file I believe it should work (i.e. `flutter pub upgrade`)

**Comment by insignity** [comment]
Thank you for responding. I fixed it. The problem was with removing webview_flutter package from pubspec.yaml and expecting it to work. Because I don't really use flutter_webview in my project. I suppose that some my package depends on it and it couldn't find in dowloaded packages. Sorry for disturbing. I am closing the issue.
