### ISSUE TITLE
How to setup audio session for alarm ringtones?

### ISSUE THREAD

**Issue by AhsanSarwar45** [ryanheise/audio_session#81]
I am creating an alarm clock application and using [just_audio ](https://pub.dev/packages/just_audio) to play the alarm ringtones. I want the app to use the system alarm volume for the ringtones. Here is the setup that I currently have:

```dart
final session = await AudioSession.instance;
await session.configure(const AudioSessionConfiguration(
  avAudioSessionCategory: AVAudioSessionCategory.playback,
  avAudioSessionCategoryOptions:
      AVAudioSessionCategoryOptions.defaultToSpeaker,
  androidAudioAttributes: AndroidAudioAttributes(
    flags: AndroidAudioFlags.audibilityEnforced,
    usage: AndroidAudioUsage.alarm,
  ),
));
_player = AudioPlayer();
await _player?.setAudioSource(AudioSource.uri(ringtoneUri));
await _player?.setLoopMode(loopMode);
_player?.play();
```
On some devices that I have tested (Android 6 and 8), it uses the phone ringtone volume, while on others (Android 11), it uses the alarm volume. 

What is the correct method to do it, so it uses the alarm volume on all devices?

**Comment by ryanheise** [comment]
This is probably not the best place to ask for help since this issues board is used for submitting issues. I would suggest first searching on StackOverflow for questions in terms of the corresponding native platform APIs (which this plugin simply mirrors), and if the question has not already been asked, you can ask a new question there.
