### ISSUE TITLE
[Help]Is there a way to force using the built-in mic？（IOS &Android）

### ISSUE THREAD

**Issue by cddqssc** [ryanheise/audio_session#83]
Is there a way to force  using the built-in mic, even when other devices are connected, such as bluetooth headsets

**Comment by ryanheise** [comment]
Since audio_session directly exposes the native APIs for iOS and Android (AVAudioSession and AudioManager), there are really two questions here maybe requiring different expertise. I would suggest asking two questions on StackOverflow, one for AVAudioSession and one for AudioManager. Of course, first search on StackOverflow since your question may already be answered.
