### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by szakarias** [ryanheise/audio_session#99]
Thanks for adding topics to your package!

Due to a bug, we were not validating the names on package upload. This is being fixed and will soon be enforced.

The guidelines for choosing topic names is https://dart.dev/tools/pub/pubspec#topics. Concretely we do not allow uppercase characters.

Could you please update your topics names in the pubspec?

Thanks in advance.

**Comment by ryanheise** [comment]
> Due to a bug, we were not validating the names on package upload. This is being fixed and will soon be enforced.

FYI, it would be more correct to say "Thanks for adding topics to your package! It looks like you added topics right after the conference announcement, but before we had actually published any documentation or guidelines on valid topic names, and we also hadn't yet updated any of our own 1st party packages to demonstrate how to do it. We have since published some guidelines, updated our own packages, and are now performing validation on pub.dev against those new guidelines. Can you please update your topic names in the pubspec?"

> Thanks in advance.

Done.

**Comment by szakarias** [comment]
Yes, and sorry for the inconvenience. Thanks for the quick update.
